[template]
src = "server.properties.tmpl"
dest = "/opt/kafka/config/server.properties"
owner = "root"
mode = "0644"
keys = [
  "/self",
  "/stacks",
]

reload_cmd = "/opt/kafka/bin/kafka-service.sh restart"
